org: gberdejo
service: pre-token

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node24
    platform: node
    external:
      - '@aws-sdk/*'

custom:
  stage: ${opt:stage, 'dev'}
  env: ${file(config/${self:custom.stage}.yml)}
  lambdaName: pre-token

provider:
  name: aws
  runtime: nodejs24.x
  stage: ${self:custom.stage}
  environment: ${self:custom.env}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource:
            - Fn::Sub: 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/tbl-users-${self:custom.stage}'
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions: ${file(config/functions.yml)}

resources:
  Resources:
    PreTokenLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:custom.stage}-${self:custom.lambdaName}
        LogGroupClass: INFREQUENT_ACCESS
