org: gberdejo
service: pre-token

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node24
    platform: node
    external:
      - '@aws-sdk/*'

custom:
  stage: ${opt:stage, 'dev'}
  env: ${file(config/${self:custom.stage}.yml)}
  lambdaName: pre-token

provider:
  name: aws
  runtime: nodejs24.x
  stage: ${self:custom.stage}
  environment: ${self:custom.env}
  iam:
    role: arn:aws:iam::005602595686:role/role-chapa-tu-venta-v1

functions: ${file(config/functions.yml)}

resources:
  Resources:
    PreTokenLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:custom.stage}-${self:custom.lambdaName}
        LogGroupClass: INFREQUENT_ACCESS
